### ISSUE TITLE
Switch view= Stopped working since yesterday

### ISSUE THREAD

**Issue by Swiftgti** [steveseguin/obsninja#1070]
If you wish yo view a feed that is inside a room with view=GUESTXXX will not retrieve the guest video feed, before yesterday was working fine, no view= only can retrieve feeds that are NOT inside a room.
It's possible to revert this?? Thanks

**Comment by steveseguin** [comment]
You can use https://vdo.ninja/v22/ if you need that feature urgently, but at present this is the intended behaviour.  

I can consider changing it, but the issue is I don't want a transfer room to be able to load a video in the main room before it has been transferred. This was causing an issue for other users.

I might be able to change it so those not in a room can view what is inside a room, but why would you need this?  If you add &solo to the view link,  `?view=GUESTXXX&solo&room=yourroom`, it should let you see that stream.

Let me know the reason and I'll make the change if there isn't a better option. Thank you

**Comment by Swiftgti** [comment]
Hi Steve, you are genius, the link you suggested with the solo and room command works perfect, I made the modifications and works as before. Thanks for your time.
