### ISSUE TITLE
Google Chrome issue

### ISSUE THREAD

**Issue by ANV78** [steveseguin/obsninja#1100]
Hi Steve!
I meet a problem with Google Chrome. Camera on my mac is not detecting in Chrome. But in Safari no problem.
I have done all possible things with Chrome (allow mic and video, re- allow this thing again many times, delete cashe, reinstal Chrome, reset Chrome settings to default ...)  to fix it on my side but no results.
Next step this problem might be or with Chrome or with vdo.ninja.
Please help to fix it.

Here is screenshots:
**Chrome**
<img width="1279" alt="Screenshot 2023-12-03 at 18 05 07" src="https://github.com/steveseguin/vdo.ninja/assets/127944741/f82f61b8-b724-4b87-a6b8-0da0d8364d59">

**Safari**
<img width="1275" alt="Screenshot 2023-12-03 at 18 06 28" src="https://github.com/steveseguin/vdo.ninja/assets/127944741/02a18051-246b-49cf-8d13-f3aa7bd1e692">

**Comment by steveseguin** [comment]
Thank you for reporting the issue.

If the camera is in use by Safari alrady, it probably won't work on Chrome at the same time. Not sure if you can confirm Safari is fully closed first, but that might help.

You can also try https://vdo.ninja/alpha/, which might work better than production.

It might also be a permissions issue; check to ensure the permissions are allowed

![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/d902dd11-a0eb-4834-a67a-aa7727020bec)

**Comment by ANV78** [comment]
I'm definitely sure that no other browser or app is using the camera when I try to connect with Chrome.
I'm absolutely sure that I gave permission to Chrome (cam and mic). 
And this issue occurs on both platforms, usual and alpha.

**Comment by steveseguin** [comment]
If you press F12, are there red errors listed in the developer console?

If you go to the following website in Chrome, does the camera work there?
https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by ANV78** [comment]
In console:
<img width="1280" alt="Screenshot 2023-12-03 at 19 42 54" src="https://github.com/steveseguin/vdo.ninja/assets/127944741/26fcf7a1-c9f3-4069-995c-7aa1b0e7bf0d">

https://webrtc.github.io/samples/src/content/devices/input-output/
Camera in this link doesn't work in Chrome but working in Safari.

**Comment by steveseguin** [comment]
If the camera in that link doesn't work, then its not a vdo.ninja specific issue.

You can go into `chrome://settings/system` and turn off "use hardware acceleration when available". This will then reboot the browser.  It might work now.

It still not working, make sure Chrome has permissions to access  your camera and mic
![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/8fadd63c-ee83-44d8-b52a-79fa7a7cd2c3)

You can try restartign the computer, and not load Safari, but perhaps Chrome first.

If that fails, you can try to full uninstall Chrome and reinstall it:
https://support.google.com/chrome/answer/95319?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Cmac

**Comment by ANV78** [comment]
All this doesn't helped.
Will try now the last suggestion - fully uninstall the Chrome.

**Comment by ANV78** [comment]
fully uninstall Chrome doesn't helped.

**Comment by steveseguin** [comment]
Looking around online, there aren't many other options.

Someone mentions updating macOS to the newest version

As mentioned already, check that Chrome has webcam permissions
![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/177a713a-c6bd-431c-bc84-e6d641e2eb34)

turn off hardware accleration in chrome:
![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/24f87c77-5361-423e-adbe-99313472979c)

Maybe try Chrome Beta instead of Chrome. I also have the Electron Capture app, [electroncapture
](https://github.com/steveseguin/electroncapture) , which might work if Chrome-specific.


Another user suggestions running the following from Terminal, providing password as needed, then restart Chrome.
```
sudo killall appleh13camerad
sudo killall VDCAssistant 
sudo killall AppleCameraAssistant
```

Another user mentions force closing the camera process via the Activity Monitor
```
Apple Logo > Force Quit > Select All Apps > Force Quit.  
```
You'd find the app ` Camera process` or something like that, and then force quit it
![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/4302b3cd-461e-4c50-b2a4-5cb2348d2d64)

I'm not entirely sure of other options though, but if you do find a solution, please let me know.

**Comment by ANV78** [comment]
Now it's working. Thank you for your support!

I think this commands helped:
sudo killall appleh13camerad
sudo killall VDCAssistant 
sudo killall AppleCameraAssistant
