### ISSUE TITLE
UI Suggestion

### ISSUE THREAD

**Issue by rodrigograca31** [steveseguin/obsninja#1101]
Move "ACTIVE" up to the bar above?
or even remove it? since the other info on the right tells you whats going on already.

Why? it would allow for more space for the camera. (as seen in the second image)

Before: 
![Screenshot_2023-12-13-23-35-18-683_com android chrome~2](https://github.com/steveseguin/vdo.ninja/assets/1134310/defb5b6c-8414-4dc0-bafe-842710fe0f28)
After: (edited by me)
![Screenshot_2023-12-13-23-35-18-683_com android chrome~22](https://github.com/steveseguin/vdo.ninja/assets/1134310/ba7cc444-83a8-406a-bc2f-a4b8bea92d0f)

P.S. Why didnt "ACTIVE" show when I was testing it with my normal Chrome browser but shows up when Im streaming to OBS? 🤔 both come from my phone
P.S.2 Now it is showing in that top bar! 👀 but as you see in the first screenshot it was not!

**Comment by steveseguin** [comment]
Thank you for the feedback. 

Before I had the "active" element fairly hidden, but still visible in the top bar.  It is based on what is shown in OBS, whether the video is active, on deck, or live. The top-right data doesn't imply you are in OBS.

OBS v30 has a bug where "live" video sources don't get told their live, so at present it only really shows that you're ACTIVE.  When OBS fixes this bug, you'll see a red "LIVE" when the video is live in OBS.

Anyways, this "active" on its own line is a recent change, and I think it is only on alpha.  Before when it was in the top line, when you did &hidemenu, it would also hide the tally light then, Another user didn't like this fact, which is why I put it on its own line.

I'll need to fix / improve it, as I don't like having it on its own line either. I'm struggling a bit to figure out how to make this all work though.

The discussion of this was on Discord here:
https://discord.com/channels/698324796546482177/1174689737987072020/1181911516996436059

What I can do is have "ACTIVE" not visible at all, but keep the "STANDBY" and "LIVE" tally lights messages. 
I can then have the Tally light hover over the top bar instead of being part of it, however this will cover up links and messages. I suppose if you are already loaded into OBS though, hiding links doens't really matter that much

**Comment by steveseguin** [comment]
okay, so I'm going to push a change that will hide "ACTIVE", unless `&tally` is added to the URL, which will also make it all larger.

"STAND BY" and "ON AIR" will remain, however "ON AIR" won't work until OBS pushes an update.

In either case, the message will now be back at the top of the page, howver it will be on-top of the header bar, potentially hiding any message or stat. I do make an effort to put the ON AIR / STANDBY message below the header bar though when I detect there is not enough room for both.

![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/ace17bc6-9fc8-4bad-8d2a-5be6b6f46e17)

![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/5c94430c-eddf-4e1d-a2fd-de1cb2dcefe2)
