### ISSUE TITLE
Feature Request: PNG Overlay in Mixer App

### ISSUE THREAD

**Issue by lucasdegen** [steveseguin/obsninja#1109]
Hello,

**The problem**
I'm a podcaster and I want to do video for a few years now but can't seem to find the right workflow where there is me the host and guest one in my studio and guest two remote on Riverside (remote audio and video).

I was planning to install multiple OBS instance and add VDO Ninja using the Browser option in OBS and add graphic overlay's in OBS. Then record all OBS instance and do some multicam editing in post...

**Feature request**
Today I found out about VDO Ninja Mixer app. It works great! All I would love to add is a PNG to a scene. So when I have, let's say a DUO screen, with me and a guest. I love to to add and PNG (with transparent window) on top. 
There is a option to add a background to a scene but not the option for a overlay. 

Keep up the good work!

Best regards,
Lucas Degen

**Comment by steveseguin** [comment]
This is an overlay per element correct?

btw, Thank you for creating a detailed github issue for this request

**Comment by steveseguin** [comment]
I guess another question is, are you okay if this is a URL? or do you want to somehow select a local file? Local files are harder to support than URLs.

**Comment by lucasdegen** [comment]
Yes an overlay per element.
Some examples of overlay:

Example 1: https://ei.marketwatch.com/Multimedia/2020/08/05/Photos/ZH/MW-IL861_biden__20200805145100_ZH.jpg?uuid=9b03583a-d74c-11ea-a7f6-9c8e992d421e

Example 2: https://images.pond5.com/tv-news-split-screen-four-171264108_prevstill.jpeg

Example 3: https://images.pond5.com/tv-news-split-screen-anchor-footage-171227394_iconl.jpeg

Yes an URL would be great, just like when adding a background image via URL!

**Comment by steveseguin** [comment]
I pushed a change to alpha for testing: https://vdo.ninja/alpha/mixer

new field for an image overlay
![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/954acb4f-d11e-425f-9a0d-464ee6e82ea4)
In this example, I'm using this transparent image link as the overlay: https://vdo.ninja/media/avatar1.png


Result:
![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/c61f78db-25a1-4fc7-8656-155cf4375d95)

Notes:
- the overlay image does not count as content, so unless you have a background image specified, iframe, or there's a guest active, it won't show on its own
- it fits 100% width/height, stretching as needed to fit the region
- the image needs to be transparent to work as an overlay, otherwise you might as well use a background image

**Comment by lucasdegen** [comment]
I  love it thanks I really hope other users are happy with this feature and will use it.

**Comment by steveseguin** [comment]
I think there might be a bug with my code, as I'm testing it more, but I'll push an fix out soon.

Um, something I'm not 100% sure of is to have the overlay cover just the video or the entire reserved container.  Videos can be different sizes, so at the moment I'm fitting the container, which might be larger than the video.   Overall, this feature will require user feedback I think to perfect

For example,
![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/13cec9db-ae41-4df0-858e-c44dd9353b37)


But if you use &cover, then it's fine

![image](https://github.com/steveseguin/vdo.ninja/assets/2575698/16b5c649-f066-4ed1-b606-d55cc41f54f8)
