### ISSUE TITLE
Group page flashes video controls when adding a source

### ISSUE THREAD

**Issue by CyBeRoni** [steveseguin/obsninja#160]
If you're using the group page and you add a new source using the 'add to group scene' button, the video controls (play/pause, volume, etc.) flash briefly over the video.

I don't expect this page ever needs video controls, so removing `controls` from the video tag seems the easy solution. Another is to use this CSS where appropriate:

```
::-webkit-media-controls {
  display:none !important;
}
```

**Comment by steveseguin** [comment]
Some people use OBS.Ninja inside Chrome to screen grab the result; as a result, they will need to manually press play to get the video elements to work.  This occurs with macOS users, since OBS v25 doesn't support OBS.Ninja directly.

The solution I've been using is to have the video load without controls, and then enabling them after 3 seconds. This prevents them from showing during the video load process, but still leaves them available as needed when on-mouse-hovering.

I overlooked the fact when an already loaded video goes from hidden to visible; apparently it shows the control bar.

I've fixed this by hiding the control bar for 3 seconds after a video becomes visible as well as when freshly loaded.

This update should be available soon in production.
