### ISSUE TITLE
ability to add a camera feed as a director

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#192]
requested yet again.

I think I need to make the camera module reusable as a template, and disconnected from the UI.

That way I can put it anywhere I want; easier.

**Comment by ersheff** [comment]
This might be related to this feature request - it would be great to have either director functionality from a regular room view or make the director room look and act more like it does for a room participant.

One thing I end up doing a lot is constructing custom "room" URL's (multiple view IDs with my one push ID) simply because I need to share my video and see/hear everyone else (with the URL parameters I set - namely video bitrate and stereo flag). I end up not using the room/scene functionality as intended because that would mean 2 OBS.ninja windows open on my computer (1 director, 1 room push/view).

Kind of a complicated thing to address - not sure what the best solution is!

**Comment by steveseguin** [comment]
Added in the newest version https://obs.ninja/beta

It's not a full-fledge guest-like experience, but the basics are there.  Chat, choose audio/video, push-to-talk

The main difference really is that a director will NOT show up in a scene or the director's room.  It is JUST seen by the group room guests.

If you want to join the show as a guest, you can do so in a new tab or use the page: use https://obs.ninja/dual to do it that way.

I may add the dual option to all pages by default.

I welcome feedback, but any changes to beta I'll consider as a new feature request
