### ISSUE TITLE
Mac browsers limited to 720p30 camera resolution

### ISSUE THREAD

**Issue by rovertp** [steveseguin/obsninja#262]
No matter which camera source or browser is used to add a camera, the maximum resolution is 720p30 and the radio buttons that appear to try to change max resolution to 1080p are not functional.  In testing on Windows, this is not an issue.  I can pipe an OBS virtual camera or a hardware camera into obs.ninja at 1080p24 and still only see 720p30 in the "current video settings" when setting up the camera feed.

<img width="549" alt="Screen Shot 2020-08-28 at 4 40 52 PM" src="https://user-images.githubusercontent.com/70416244/91622941-499d7c00-e94e-11ea-9a54-3d6abeed0106.png">

**Comment by steveseguin** [comment]
I'm aware that iOS limits the resolution to 720p30, so it's possible that I'm incorrectly detecting a Mac system as an iOS system.

Would you be able to run the following bit of code and let me know the result?
[https://jsfiddle.net/steveseguin/46dwsx9v/5/](https://jsfiddle.net/steveseguin/46dwsx9v/5/)

If the result is " false : 0 ", would you instead go to [https://webrtchacks.github.io/WebRTC-Camera-Resolution/](https://webrtchacks.github.io/WebRTC-Camera-Resolution/) and let me know if 1920x1080 passes in the "Quick Scan" test?

![image](https://user-images.githubusercontent.com/2575698/91623227-8f673e00-e968-11ea-96c1-2214559db748.png)

thank you!

**Comment by rovertp** [comment]
false : 0

Checking this on another system running MacOS 10.15 and it is fine -
showing 1080.  Could be related to Mac Os 10.14.  Still exploring.

Thanks so much for your tools.  We are hoping to deploy on our own servers
soon.  I think you're hosting your signal server on Google?  We're setting
up on AWS.

Best,
Trevor


[image: Fridays Web Site] <http://fridaysfilms.com/>

FRIDAYS

Trevor Pressman

CTO & Head of Post Production

+1 415.345.9596 (O)
[image: Fluidity] <http://fridaysfilms.com/> [image: Fluidity]
<https://vimeo.com/fridaysfilms> [image: Fluidity]
<https://www.facebook.com/FridaysFilmsProductions/>

**Comment by rovertp** [comment]
Screenshots attached of first and second test pages.

Trevor

[image: Fridays Web Site] <http://fridaysfilms.com/>

FRIDAYS

Trevor Pressman

CTO & Head of Post Production

+1 415.345.9596 (O)
[image: Fluidity] <http://fridaysfilms.com/> [image: Fluidity]
<https://vimeo.com/fridaysfilms> [image: Fluidity]
<https://www.facebook.com/FridaysFilmsProductions/>

**Comment by steveseguin** [comment]
Not sure I got the screen shots.  You can email them to me directly tho at steve@seguin.email

**Comment by rovertp** [comment]
Another shot in firefox.  Hopefully it's a browser detect error... that
would be great.

Trevor

[image: Fridays Web Site] <http://fridaysfilms.com/>

FRIDAYS

Trevor Pressman

CTO & Head of Post Production

+1 415.345.9596 (O)
[image: Fluidity] <http://fridaysfilms.com/> [image: Fluidity]
<https://vimeo.com/fridaysfilms> [image: Fluidity]
<https://www.facebook.com/FridaysFilmsProductions/>

**Comment by steveseguin** [comment]
From what I see of the screen shots you sent me (thank you), the Wirecast virtual camera you are using is not allowing higher resolutions than 720p.

This might be due to the Wirecast Canvas resolution you have set; is it 1080p or 720p? I'm not too familiar with Wirecast, nor Macs, so I'm not too sure I can help there.

Do any of the other webcam sources support 1080p? or is it just Wirecast?  If the webcam is being used by another app, close that app and see if it increases in the resolution testing tool. Sometimes another application will limit the resolution.

It's hard to say in full confidence, but from the looks of it this isn't an issue with OBS.Ninja itself. 

![image](https://user-images.githubusercontent.com/2575698/91624684-8e85da80-e96f-11ea-9f5c-6aeea6270dd2.png)
