### ISSUE TITLE
Autoplay in screen share view mode doesn't work on Chrome Browser

### ISSUE THREAD

**Issue by tsioukas** [steveseguin/obsninja#316]
Autostart when you are viewing a screen share doesn't work on Chrome (v.85.x). On Firefox (v80.0.1) and OBS autostart work like a charm. I didn't test it but maybe the same will be for webcam autostart. Just to clarify on view mode not in push mode.

Also can you add options on URL on push mode to disable some features. For example chat, settings and other like some buttons on the bottom bar.

P.S. Just a tip for vMix users, use v62 browser not v77. Autostart will work.

**Comment by steveseguin** [comment]
Auto start does not work in Chrome or Firefox due to autoplay policies: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

I've disabled those policies in the Electron app and they are already disabled in OBS.

This is not something I can fix, although you can load up Chrome with a CLI parameter that will allow for autoplay.


As for hiding UI elements, there is a URL parameter for this -- &cleanoutput , although there are some others that hide different things. Please see: https://github.com/steveseguin/obsninja/wiki/Advanced-Settings#general-options

**Comment by steveseguin** [comment]
if vMix does not auto start, please submit a feature request to vmix.  I think I did this before actually, on their support forums.


fyi
```
 --autoplay-policy=no-user-gesture-required
```

**Comment by steveseguin** [comment]
https://forums.vmix.com/posts/t22181-CEF-V77-browser-setting

and here is the link to the Vmix issue.

**Comment by tsioukas** [comment]
You are GREAT!!! Thank you... I didn't know about chrome policy and I was too blind (from codding) that I didn't see &cleanoutput parameter ;)

**Comment by steveseguin** [comment]
There's a new flag, &cleanish , that keeps the "play button" overlay , while hiding other UI elements.   It's otherwise just like the &clean flag.  It might be helpful for those using VMIX and those who want to maintain a playbutton to help them remember to hit play.
