### ISSUE TITLE
OBS 25 [Linux]- the stream doesn't show up using the brower source

### ISSUE THREAD

**Issue by jprobichaud** [steveseguin/obsninja#32]
What a great tool!  Thanks for this contribution!

I'm trying to follow the instructions and put the http url in a Linux Browser source (I've tried the QtWebkit too) and it seems that the video doesn't "start".  I've tried the "old" and "beta" websites, without success.  I notice that when going with a regular browser to the url given by obs.ninja, I have to press the "play" button for the stream to start.  Could that be the problem?  We can't really "interact" with the webpage from obs (at least, it didn't gave me that possibility when I tried).

I'm on Arch Linux, 64 bits, with obs studio 25

**Comment by dodgepong** [comment]
How did you install OBS?

**Comment by jprobichaud** [comment]
From the AUR repository (arch linux user repo).

Anything special i should look fornin the installation method?

**Comment by dodgepong** [comment]
Well, the AUR is not an official source, so it's possible they haven't built it in a way that would make it work. The only official package is the Ubuntu PPA.

Also, it sounds like you're using the obs-linuxbrowser plugin rather than the official browser plugin, is that correct?

Can you post a log from OBS, and also make a browser source, point the URL to `chrome://version`, and post a screenshot of the output? (You may need to create a white Color Source behind it to read the black text)
