### ISSUE TITLE
Report button unintentionally displayed in https://rtc.ninja/beta?

### ISSUE THREAD

**Issue by verstaerker-583** [steveseguin/obsninja#653]
There is probably a line missing in [https://obs.ninja/beta/main.js](https://obs.ninja/beta/main.js)?

```javascript
  getById("helpbutton").style.display = "none";
  getById("helpbutton").style.opacity = 0;
  getById("reportbutton").style.display = "none";
+ getById("reportbutton").style.opacity = 1;
  getById("mainmenu").style.opacity = 1;
```

**Comment by steveseguin** [comment]
Thank you for reporting an issue.

I don't understand what the problem is however.   

The error-report button shows if an error occurs within the app.

It uses the CSS: 
```
getById("reportbutton").style.visibility = "visible";  
``` 
to toggle on or off.

Just to be safe, I've added
```
#reportbutton{
	visibility: hidden;
}
```
to the main.css file. It is already set to visiblity=hidden inline with the element.

My understanding then is you don't want the report button to show up at all with rtc.ninja?

Would you not want to set getById("reportbutton").style.opacity = 0; then instead of 1?

I'm happy to make the change, so it doesn't show up.

I'll also add code so it hides if I detect you are using an IFRAME.

**Comment by steveseguin** [comment]
I pushed this update to beta.

- I perma-hide the error report button on rtc.ninja
- if I detect the site is within an IFRAME, I perma-hide the info-button, the report-error button, and clear the chat's welcome message.  This also applies to obfuscated links via invite.cam

**Comment by verstaerker-583** [comment]
Steve,

that was fast - thank you very much!

Sorry - yes, I should have written getById("reportbutton").style.opacity = **0**

Best Regards,

Olaf
