### ISSUE TITLE
Add video delay

### ISSUE THREAD

**Issue by b00rek** [steveseguin/obsninja#67]
If you need to sync video from OBS.ninja with a different streaming audio source, and video comes earlier than audio, you need a way to +offset the video.

**Comment by steveseguin** [comment]
It's funny, because in 99% of situations the video lags behind the audio.

**Comment by b00rek** [comment]
Found out that you can use "render delay" filter with browser source in OBS, which offsets only video, but not audio, for a maximum of +500ms. At least it behaves that way in version 25.0.4. 

Problem with that solution is, with render delay set, you can't trust video preview/audio monitor in OBS anymore. For example: set a render delay to +500ms. Set audio delay to +500 ms. Watch the preview & listen to monitored audio. They will be delayed, but not even remotely in sync. Record that and watch the recording: video+audio will be perfectly in sync. But that's a bug in OBS, so I'd either make this feature request the bottom of the list priority, or mark it wontfix.

**Comment by steveseguin** [comment]
I've added the option, in Alpha, to add a "buffer".  While you can use this to add a fixed and accurate delay to the media, the main use case would be to improve video playback stability. Very useful if doing 1080p60 over the internet.

I'm trying to add a way to offer, on top of that, a "sync" value, which will delay the audio OR video based on whether it is positive or negative.  I've had two people make this request now, so I figure I'll just add it in.

I will eventually use this code to also "auto sync" audio and video streams that fall out of sync due to poor CPU or network performance. A few users have had issues there.
