### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KovalevArtem** [steveseguin/obsninja#73]
It is sad that the service is only in English - I propose to translate.
I am ready to help in the translation into Russian.
(For example, you can use Weblate, Crowdin, or any other service. Free for open source projects.)

**Comment by steveseguin** [comment]
It's a great idea.  What I can do is add the framework to the code, and let others contribute their own translations.

**Comment by KovalevArtem** [comment]
@orangesunny Need help!

**Comment by orangesunny** [comment]
Hi! We will be happy to host the translations. Once you have at least the base file in your repo, please, let us know on https://hosted.weblate.org/hosting/, and we will set up the translation project.

As you have it mostly HTML and JS, I suppose you’ll use i18next, but feel free to choose any other according to its specifics: https://docs.weblate.org/en/latest/formats.html

Translate libre, and have a great day!

**Comment by steveseguin** [comment]
So I took a first stab at making a localization implementation.  

It can be used like this:
https://obs.ninja/alpha?ln=fr_ca

I've created some example translation files.  They do not get used unless specified.  
https://github.com/steveseguin/obsninja/tree/master/translations

I liked my approach here as it lets me continue to develop the code base without a lot of clutter and without worrying about breaking existing language sets.

I've yet to add a menu or option to select these translations, but they are not at least available as options.  This code has been committed to master.

**Comment by KovalevArtem** [comment]
@comradekingu Join in 😏

**Comment by comradekingu** [comment]
Crowdin isn't free for libre software. Only if contributing to the closed TM, and only for projects that have no source of revenue. Weblate is a lot better in all aspects. Either self-hosted or the "Hosted Weblate" service, which actually is gratis for libre software, and worth every bit of attention and money one can throw at it, seeing as it is actually copylefted libre software, without any nonsense.

**Comment by KovalevArtem** [comment]
> I've created some example translation files. They do not get used unless specified.
> https://github.com/steveseguin/obsninja/tree/master/translations
@orangesunny

**Comment by steveseguin** [comment]
It now uses the **_ru.json_** translation file if a **_ru-*_** locale is detected by your browser.

If Russian is the default language in chrome, then it will auto-translate.
Chrome->Settings -> languages -> Russian (pin to top)

You can manually select Russian, but using the &ln=ru parameter to the URL. ie:
https://obs.ninja/alpha/?ln=ru

result:

![image](https://user-images.githubusercontent.com/2575698/81628910-f5d34b00-93cf-11ea-88fb-59dd37ce1411.png)

I've also applied a French translation.  English is the default, and so the English translation file is purely for reference.

Both the French and Russian translation files are created using Google Translate and are pretty bad.  

Please feel to fix any poor translation by editing the following file and submitting a PR: https://github.com/steveseguin/obsninja/blob/master/translations/ru.json

I don't really see a need to use Webplate, as it seems a bit overkill for such a simple website. I would ultimately like to have as little text as possible on OBS.Ninja, so the goal should be finding ways to remove text, rather than translating it. ie) making it more intuitive and easier to use.

**Comment by comradekingu** [comment]
@steveseguin 
You will get a lot more translations, and better ones at that. If you start removing text, having a platform is a godsend, seeing as things otherwise get inconsistent quick.
If you want to expand to a blog or post changelogs, there is a lot more to translate.
I can already tell "macOS" is written "MacOS", and running fixes becomes a lot quicker with alerts, along with finding errors with all the checks.

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/86175923-d386bf80-bb2c-11ea-8c28-75aec6116b7e.png)
@steveseguin It seems to me that the files are redundant _blank.json_ and _default.json_. In a sense, this complicates the selection of the start file for the translator. And for the developer complicates keeping the files up to date ...
I think most will obviously take the **en.json** file as the basis.
And if someone suddenly does not know English, then he can take as a basis a file with a language familiar to him ...

**Comment by jcalado** [comment]
Latest releases of OBS.Ninja have full-featured localization. V16 even improves this further.
Closing as fixed.
