### ISSUE TITLE
Right click edit link option in electron

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/obsninja#773]
theotherlonestarToday

**Comment by lindenkron** [comment]
Yes I was looking for this option. Having to close the electron app, to re-open it while having already selected it in windowed mode in OBS is quite a problem since you'll have to go to the scene and select the proper OBSN window again once you make a new instance. The ability to edit the link would be 10/10.

**Comment by steveseguin** [comment]
You can right click, select go home, then enter the new address there.

The ability to edit it though might be a bit more user friendly, especially if you don't recall what the URL parameters were

**Comment by jcalado** [comment]
This has been included on the app. 👍
