### ISSUE TITLE
rtc.ninja website text remove

### ISSUE THREAD

**Issue by Swiftgti** [steveseguin/obsninja#981]
Its possible to take out the legend in rtc.ninja website, when using the Share your screen option, after selecting the screen without audio. the legend with text:
No Audio Source was detected.

**Remove This Part:**
If you were wanting to capture an Application's Audio, please see:
https://docs.vdo.ninja/help/guides-and-how-tos#audio for some guides.

Thanks!

**Comment by steveseguin** [comment]
I updated the translations on github and on alpha with this change
![image](https://user-images.githubusercontent.com/2575698/186053410-5f8943a5-b7ed-4bb0-a171-e764ad5ca4a8.png)

https://rtc.ninja/alpha/?screenshare

If you need it added to production for some reason soon, I can try to hot-patch it, but otherwise it will go live on production when I push alpha into production in the future.

**Comment by Swiftgti** [comment]
Hi thank you. It will be grate if you can hot-patch because I need to publish it. 

Thank you very much, have a good night.
